[package]
name = "mdbookshelf"
version = "0.1.3"
authors = ["Ramses Ladlani <rladlani@gmail.com>"]
description = "Create epubs from a list of mdbook repositories"
documentation = "https://docs.rs/mdbookshelf/"
repository = "https://github.com/rams3s/mdbookshelf"
keywords = ["epub", "ebook", "mdbook", "rustbook"]
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
chrono = "0.4.6"
clap = "3.2"
color-backtrace = "0.5"
env_logger = "0.9"
git2 = "0.15"
log = "0.4"
mdbook = "0.4.21"
mdbook-epub = { git = "https://github.com/dieterplex/mdbook-epub", rev = "76416d71" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1"
toml = "0.5.0"
url = "2.3"
walkdir = "2.2"
