[package]
name = "mdbook-library"
version = "0.1.0"
authors = ["Ramses Ladlani <rladlani@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
env_logger = "0.6.1"
git2 = "0.8.0"
log = "0.4.6"