# Build cross image with openssl support
# see https://github.com/cross-rs/cross/pull/322
[target.x86_64-unknown-linux-gnu.dockerfile]
file = "./docker/Dockerfile.x86_64-unknown-linux-gnu"
context = "."

[target.x86_64-unknown-linux-musl.dockerfile]
file = "./docker/Dockerfile.x86_64-unknown-linux-musl"
context = "."
