FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest
ARG DEBIAN_FRONTEND=noninteractive

COPY ./docker/openssl.sh /
RUN bash /openssl.sh linux-x86_64

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner x86_64" \
    OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib